package com.example.syntaxappproject.ui;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import androidx.annotation.NonNull;

import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import org.junit.Test;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

// Test generated by ChatGPT on 3/13/26, 3:52 pm with prompt "write me a test for sending something to firebase and retrieving it please"
// Tests sending and retrieving a Strring from Firebase
public class TestFirebaseConnection {
    @Test
    public void writeAndReadBackValue() throws InterruptedException {
        FirebaseDatabase database = FirebaseDatabase.getInstance();
        DatabaseReference ref = database.getReference("test/messages").child("Test");

        String expected = "hello firebase";
        CountDownLatch latch = new CountDownLatch(1);

        ref.setValue(expected)
                .addOnSuccessListener(unused -> {
                    ref.addListenerForSingleValueEvent(new ValueEventListener() {
                        @Override
                        public void onDataChange(@NonNull DataSnapshot snapshot) {
                            String actual = snapshot.getValue(String.class);
                            assertEquals(expected, actual);
                            latch.countDown();
                        }

                        @Override
                        public void onCancelled(@NonNull DatabaseError error) {
                            fail("Read cancelled: " + error.getMessage());
                            latch.countDown();
                        }
                    });
                })
                .addOnFailureListener(e -> {
                    fail("Write failed: " + e.getMessage());
                    latch.countDown();
                });

        if (!latch.await(10, TimeUnit.SECONDS)) {
            fail("Timed out waiting for Firebase response");
        }
    }
}
